function PlotRange(S)

    FB = [178, 34, 34] / 255;

    Re = PlanetaryRadii({'Earth'});

    OrbitColor = {'k',FB,'k', FB, 'k', FB};

    n = numel(S);
    % []Number of elements in the time vector.

    maxRange = round(max(S(4).r) / Re, 0) + 5;

    %-----------------------------------------------------------------------------------------------

    Window = figure( ...
        'Color','w', ...
        'Name','Range Analysis', ...
        'NumberTitle','Off');
    % []Opens a new window and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    Axes = axes( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'Parent',Window, ...
        'XGrid','On', ...
        'YGrid','On', ...
        'XLim',[0, 30], ...
        'YLim',[0,maxRange], ...
        'XTick',linspace(0,30,16), ...
        'YTick',linspace(0,maxRange,16));
    % []Adds an axes to the specified window and adjusts its properties.

    title( ...
        'Range Analysis', ...
        'FontSize',20, ...
        'Parent',Axes);
    % []Adds a title to the specified axes and adjusts its properties.

    xlabel( ...
        'Time (Solar Days)', ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a label to the specified x-axis and adjusts its properties.

    ylabel( ...
        'Range (Earth Radii)', ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a label to the specified y-axis and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    for k = 1:n

        plot(S(k).t / 3600 / 24, S(k).r / Re, ...
            'Color',OrbitColor{k}, ...
            'LineStyle','-', ...
            'Marker','.', ...
            'Parent',Axes);
        % []Adds a plot to the specified axes and adjusts its properties.
    
        hold on

    end


end