function PlotCr3bp(S,C)
    
    FB = [178, 34, 34] / 255;

    OrbitColor = {'k',FB,'k', FB, 'k', FB};

    Re = C.Re / C.r12;
    %[]Normalized mean equatorial radius of the Earth.
    
    Rm = C.Rm / C.r12;
    %[]Normalized mean equatorial radius of the Moon.
    
    %-----------------------------------------------------------------------------------------------
    
    [xe,ye,ze] = ellipsoid(-C.lambda,0,0,Re,Re,Re,100);
    %[]Coordinates for the Earth.
    
    [xm,ym,zm] = ellipsoid(1 - C.lambda,0,0,Rm,Rm,Rm,100);
    %[]Coordinates for the Earth.
    
    %-----------------------------------------------------------------------------------------------
    
    Earth = imread('Earth.png');
    %[]Loads the image of the Earth.
    
    Moon = imread('Moon.png');
    %[]Loads the image of the Earth.
    
    %-----------------------------------------------------------------------------------------------
    
    ScreenSize = get(0,'ScreenSize');
    %[]Determines the location and dimensions of the current monitor.
    
    Window = figure( ...
        'Color','w', ...
        'Name','Trajectory in the Circular Restricted Three-Body Problem', ...
        'NumberTitle','Off', ...
        'OuterPosition',ScreenSize);
    %[]Opens a new window and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    Extent = 1.2;
    %[]Axes extent.
    
    Axes = axes( ...
        'FontName','Arial', ...
        'FontSize',8, ...
        'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'Parent',Window, ...
        'PlotBoxAspectRatio',[1,1,1], ...
        'XGrid','On', ...
        'YGrid','On', ...
        'ZGrid','On', ...
        'XLim',Extent * [-1,1], ...
        'YLim',Extent * [-1,1], ...
        'ZLim',Extent * [-1,1], ...
        'XTick',Extent*(-1:0.1:1), ...
        'YTick',Extent*(-1:0.1:1), ...
        'ZTick',Extent*(-1:0.1:1));
    %[]Adds an axes to the specified window and adjusts its properties.
    
    title('Lagrange Point Tour','FontSize',16,'Parent',Axes);
    %[]Adds a title to the specified axes and adjusts its properties.
    
    xlabel('\chi_x','FontSize',12,'Parent',Axes);
    %[]Adds a label to the x-axis and adjusts its properties.
    
    ylabel('\chi_y','FontSize',12,'Parent',Axes);
    %[]Adds a label to the y-axis and adjusts its propeties.
    
    %-----------------------------------------------------------------------------------------------

    surface(xe,ye,-ze, ...
        'CData',Earth, ...
        'EdgeColor','None', ...
        'FaceColor','TextureMap', ...
        'Parent',Axes);
    %[]Adds a plot to the specified axes and adjusts its properties.
    
    surface(xm,ym,-zm, ...
        'CData',Moon, ...
        'EdgeColor','None', ...
        'FaceColor','TextureMap', ...
        'Parent',Axes);
    %[]Adds a plot to the specified axes and adjusts its properties.

    %-----------------------------------------------------------------------------------------------
    
    text( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'HorizontalAlignment','Center', ...
        'Parent',Axes, ...
        'Position',[0.83691513,-0.1,0], ...
        'String','L_1');
    %[]Adds a textbox to the specified axes.
    
    text( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'HorizontalAlignment','Center', ...
        'Parent',Axes, ...
        'Position',[1.15568216,-0.1,0], ...
        'String','L_2');
    %[]Adds a textbox to the specified axes.
    
    text( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'HorizontalAlignment','Center', ...
        'Parent',Axes, ...
        'Position',[-1.00506265,-0.1,0], ...
        'String','L_3');
    %[]Adds a textbox to the specified axes.
    
    text( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'HorizontalAlignment','Center', ...
        'Parent',Axes, ...
        'Position',[0.5 - C.lambda,sqrt(3) / 2 + 0.1,0], ...
        'String','L_4');
    %[]Adds a textbox to the specified axes.
    
    text( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'HorizontalAlignment','Center', ...
        'Parent',Axes, ...
        'Position',[0.5 - C.lambda,-(sqrt(3) / 2 + 0.1),0], ...
        'String','L_5');
    %[]Adds a textbox to the specified axes.
    
    %-----------------------------------------------------------------------------------------------
    
    text( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'HorizontalAlignment','Center', ...
        'Parent',Axes, ...
        'Position',[-C.lambda,0.1,0], ...
        'String','Earth');
    %[]Adds a textbox to the specified axes.
    
    text( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'HorizontalAlignment','Center', ...
        'Parent',Axes, ...
        'Position',[1 - C.lambda,0.1,0], ...
        'String','Moon');
    %[]Adds a textbox to the specified axes.
    
    %-----------------------------------------------------------------------------------------------
    
    plot(0.83691513,0, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'MarkerSize',25, ...
        'Parent',Axes);
    %[]Adds a plot to the specified axes and adjusts its properties.
    
    plot(1.15568216,0, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'MarkerSize',25, ...
        'Parent',Axes);
    %[]Adds a plot to the specified axes and adjusts its properties.
    
    plot(-1.00506265,0, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'MarkerSize',25, ...
        'Parent',Axes);
    %[]Adds a plot to the specified axes and adjusts its properties.
    
    plot(0.5 - C.lambda,sqrt(3) / 2, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'MarkerSize',25, ...
        'Parent',Axes);
    %[]Adds a plot to the specified axes and adjusts its properties.
    
    plot(0.5 - C.lambda,-sqrt(3) / 2, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'MarkerSize',25, ...
        'Parent',Axes);
    %[]Adds a plot to the specified axes and adjusts its properties.
    
    %-----------------------------------------------------------------------------------------------

    n = numel(S);
    % []Number of mission segments.

    for k = 1:n

        R3cm = S(k).R3cm / C.r12;
        % []Normalizes the satellite positions WRT the CM in CR3BP coordinates.

        plot3(R3cm(1,:),R3cm(2,:),R3cm(3,:), ...
            'Color', OrbitColor{k}, ...
            'LineStyle','None', ...
            'Marker','.', ...
            'Parent',Axes);
        %[]Adds a plot to the specified axes and adjusts its properties.

    end
    
end
%===================================================================================================