function R = PlotTrajectory(Solution,C,Title)

    JDo = C.JDo + Solution.x / 86400;
    % [solar days]Transfer Julian date vector.

    JD = linspace(JDo(1),JDo(end),7000);
    % [solar days]Updates the Julian date vector.

    %-----------------------------------------------------------------------------------------------

    R.R1cm = transpose(interp1(C.Sun.JD,transpose(C.Sun.R),JD,'Spline'));
    % [km]Sun position WRT the CM in ECI coordinates.

    R.R2cm = transpose(interp1(C.Earth.JD,transpose(C.Earth.R),JD,'Spline'));
    % [km]Earth position WRT the CM in ECI coordinates.

    R.R3cm = transpose(interp1(C.Moon.JD,transpose(C.Moon.R),JD,'Spline'));
    % [km]Moon position WRT the CM in ECI coordinates.

    R.R4cm = transpose(interp1(C.Mars.JD,transpose(C.Mars.R),JD,'Spline'));
    % [km]Mars position WRT the CM in ECI coordinates.

    R.R5cm = transpose(interp1(C.Jupiter.JD,transpose(C.Jupiter.R),JD,'Spline'));
    % [km]Jupiter position WRT the CM in ECI coordinates.

    R.R6cm = transpose(interp1(C.Ganymede.JD,transpose(C.Ganymede.R),JD,'Spline'));
    % [km]Ganymede position WRT the CM in ECI coordinates.

    R.R7cm = transpose(interp1(C.Callisto.JD,transpose(C.Callisto.R),JD,'Spline'));
    % [km]Callisto position WRT the CM in ECI coordinates.

    R.R8cm = transpose(interp1(C.Io.JD,transpose(C.Io.R),JD,'Spline'));
    % [km]Io position WRT the CM in ECI coordinates.

    R.R9cm = transpose(interp1(C.Europa.JD,transpose(C.Europa.R),JD,'Spline'));
    % [km]Europa position WRT the CM in ECI coordinates.

    R.R10cm = transpose(interp1(JDo,transpose(Solution.y(1:3,:)),JD,'Spline'));
    % [km]Satellite position WRT the CM in ECI coordinates.
    %-----------------------------------------------------------------------------------------------

    R21 = (R.R2cm - R.R1cm) / C.AU;
    % [AU]Earth position WRT the Sun in ECI coordinates.

    R41 = (R.R4cm - R.R1cm) / C.AU;
    % [AU]Earth position WRT the Sun in ECI coordinates.

    R51 = (R.R5cm - R.R1cm) / C.AU;
    % [AU]Jupiter position WRT the Sun in ECI coordinates.

    R101 = (R.R10cm - R.R1cm) / C.AU;
    % [AU]Satellite position WRT the Sun in ECI coordinates.

    %-----------------------------------------------------------------------------------------------

    ScreenSize = get(0,'ScreenSize');

    Window = figure( ...
        'Color','w', ...
        'Name','Interplanetary Trajectory', ...
        'NumberTitle','Off', ...
        'OuterPosition',ScreenSize);
    % []Opens a new window and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    Extent = 6;
    % [AU]Axis limits.

    Axes = axes( ...
        'Color','w', ...
        'DataAspectRatio',[1,1,1], ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'Parent',Window, ...
        'XGrid','On', ...
        'YGrid','On', ...
        'ZGrid','On', ...
        'XLim',Extent * [-1,1], ...
        'YLim',Extent * [-1,1], ...
        'Zlim',Extent * [-1,1], ...
        'XTick',Extent * linspace(-1,1,13), ...
        'YTick',Extent * linspace(-1,1,13), ...
        'ZTick',Extent * linspace(-1,1,13));
    % []Adds an axes to the specified window and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    title( ...
        Title, ...
        'FontSize',20, ...
        'Parent',Axes);
    % []Adds a title to the specified axes and adjusts its propeties.

    xlabel( ...
        'X-Axis (AU)', ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a label to the specified x-axis and adjusts its propeties.

    ylabel( ...
        'Y-Axis (AU)', ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a label to the specified y-axis and adjusts its propeties.

    %-----------------------------------------------------------------------------------------------

    plot3(R21(1,:),R21(2,:),R21(3,:), ...
        'Color','b', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots the Earth during the transfer.

    plot3(R41(1,:),R41(2,:),R41(3,:), ...
        'Color','#B22222', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots Mars during the transfer.

    plot3(R51(1,:),R51(2,:),R51(3,:), ...
        'Color','#1247F3', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots Jupiter during the transfer.

    plot3(R101(1,:),R101(2,:),R101(3,:), ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots the satellite during the transfer.

    %-----------------------------------------------------------------------------------------------

    legend({'Earth','Mars', 'Jupiter','Satellite'});
    % []Adds a legend to the plot.

    theme 'light'

end
%===================================================================================================