function PlotDepartureTrajectory(R, C,Title)

    n = size(R.R10cm,2);
    % []Number of orbital data points.

    R32 = (R.R3cm - R.R2cm) / C.R(2);
    % [Earth radii]Moon positions WRT the Earth in ECI coordinates.

    R102 = (R.R10cm - R.R2cm) / C.R(2);
    % [Earth radii]Satellite positions WRT the Earth in ECI coordinates.

    for k = 1:n

        if norm(R102(:,k)) >= 150

            R32(:,k) = nan * ones(3,1);
            % []Position is ignored because the satellite is outside of Earth's SOI.

            R102(:,k) = nan * ones(3,1);
            % []Position is ignored because the satellite is outside of Earth's SOI.


        end

    end

    %-----------------------------------------------------------------------------------------------

    Window = figure( ...
        'Color','w', ...
        'Name','Earth Departure Trajectory', ...
        'NumberTitle','Off');
    % []Opens a new window and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    Extent = 150;
    % [Earth radii]Axes limits.

    Axes = axes( ...
        'Color','w', ...
        'DataAspectRatio',[1,1,1], ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'Parent',Window, ...
        'XGrid','On', ...
        'YGrid','On', ...
        'ZGrid','On', ...
        'XLim',Extent * [-1,1], ...
        'YLim',Extent * [-1,1], ...
        'ZLim',Extent * [-1,1], ...
        'XTick',Extent * linspace(-1,1,11), ...
        'YTick',Extent * linspace(-1,1,11), ...
        'ZTick',Extent * linspace(-1,1,11));
    % []Adds an axes to the specified window and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    title( ...
        Title, ...
        'FontSize',20, ...
        'Parent',Axes);
    % []Adds a title to the specified axes and adjusts its propeties.

    xlabel( ...
        'X-Axis (R_e)', ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a label to the specified x-axis and adjusts its propeties.

    ylabel( ...
        'Y-Axis (R_e)', ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a label to the specified y-axis and adjusts its propeties.

    %-----------------------------------------------------------------------------------------------

    plot3(R32(1,:),R32(2,:),R32(3,:), ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots the Earth during the transfer.

    plot3(R102(1,:),R102(2,:),R102(3,:), ...
        'Color','r', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots the satellite during the transfer.

    %-----------------------------------------------------------------------------------------------

    legend({'Moon','Satellite'});
    % []Adds a legend to the plot.

    theme 'light'
end
%===================================================================================================