function PlotArrivalTrajectory(R,C,Title)

    n = size(R.R10cm,2);
    % []Number of orbital data points.

    R65 = (R.R6cm - R.R5cm) / C.R(5);
    % [Jupiter radii] Ganymede positions WRT Jupiter in ECI coordinates.

    R75 = (R.R7cm - R.R5cm) / C.R(5);
    % [Jupiter radii] Callisto positions WRT Jupiter in ECI coordinates.

    R85 = (R.R8cm - R.R5cm) / C.R(5);
    % [Jupiter radii] Io positions WRT Jupiter in ECI coordinates.

    R95 = (R.R9cm - R.R5cm) / C.R(5);
    % [Jupiter radii] Europa positions WRT Jupiter in ECI coordinates.

    R105 = (R.R10cm - R.R5cm) / C.R(5);
    % [Jupiter radii]Satellite positions WRT Jupiter in ECI coordinates.

    for k = 1:n

        if norm(R105(:,k)) > 150

            R65(:,k) = nan * ones(3,1);
            % []Resets the Ganymede position.

            R75(:,k) = nan * ones(3,1);
            % []Resets the Callisto position.

            R85(:,k) = nan * ones(3,1);
            % []Resets the Io position.

            R95(:,k) = nan * ones(3,1);
            % []Resets the Europa position.

            R105(:,k) = nan * ones(3,1);
            % []Resets the satellite position if outside the Jupiter sphere of influence.

        end

    end

    %-----------------------------------------------------------------------------------------------

    Window = figure( ...
        'Color','w', ...
        'Name','Jupiter Arrival Trajectory', ...
        'NumberTitle','Off');
    % []Opens a new window and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    Extent = 150;
    % [Jupiter radii]Axes limits.

    Axes = axes( ...
        'Color','w', ...
        'DataAspectRatio',[1,1,1], ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'Parent',Window, ...
        'XGrid','On', ...
        'YGrid','On', ...
        'ZGrid','On', ...
        'XLim',Extent * [-1,1], ...
        'YLim',Extent * [-1,1], ...
        'XTick',Extent * linspace(-1,1,11), ...
        'YTick',Extent * linspace(-1,1,11));
    % []Adds an axes to the specified window and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    title( ...
        Title, ...
        'FontSize',20, ...
        'Parent',Axes);
    % []Adds a title to the specified axes and adjusts its propeties.

    xlabel( ...
        'X-Axis (R_j)', ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a label to the specified x-axis and adjusts its propeties.

    ylabel( ...
        'Y-Axis (R_j)', ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a label to the specified y-axis and adjusts its propeties.

    %-----------------------------------------------------------------------------------------------

    plot3(R65(1,:),R65(2,:),R65(3,:), ...
        'Color','#77AC30', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots Europa during the transfer.

    plot3(R75(1,:),R75(2,:),R75(3,:), ...
        'Color','#3A95CB', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots Callisto during the transfer.

    plot3(R85(1,:),R85(2,:),R85(3,:), ...
        'Color','#B22222', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots Io during the transfer.

    plot3(R95(1,:),R95(2,:),R95(3,:), ...
        'Color','#E5812A', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots Europa during the transfer.

    plot3(R105(1,:),R105(2,:),R105(3,:), ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Plots the satellite during the transfer.

    %-----------------------------------------------------------------------------------------------

    legend({'Ganymede','Callisto', 'Io', 'Europa', 'Satellite'});
    % []Adds a legend to the plot.

    theme 'light'

end
%===================================================================================================