function PlotThrust(S,C)

    n = numel(S.t);
    % []Number of elements in the time vector.

    Tmag = zeros(1,n);
    % []Allocates memory for the rocket mass.

    for k = 1:n

        hcg = norm(S.R(:,k)) - C.Re;
        % [km]Altitude above mean equator.

        [~,T] = MassThrust(S.t(k),S.R(:,k),S.V(:,k),hcg,C);
        % [kN]Rocket thrust vector.

        Tmag(k) = norm(T);
        % [kN]Rocket thrust magnitude.

    end

    %-----------------------------------------------------------------------------------------------

    Window = figure( ...
        'Color','w', ...
        'Name','Thrust Profile During Launch', ...
        'NumberTitle','Off');
    % []Opens a new window and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    Axes = axes( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'Parent',Window, ...
        'XGrid','On', ...
        'YGrid','On', ...
        'XLim',[0,600], ...
        'YLim',[0,8500], ...
        'XTick',linspace(0,600,11), ...
        'YTick',linspace(0,8500,11));
    % []Adds an axes to the specified window and adjusts its properties.

    title( ...
        'Rocket Thrust Profile', ...
        'FontSize',20, ...
        'Parent',Axes);
    % []Adds a title to the specified axes and adjusts its properties.

    xlabel( ...
        'Time (s)', ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a label to the specified x-axis and adjusts its properties.

    ylabel( ...
        'Thrust (kN)', ...
        'FontSize',16, ...
        'Parent',Axes);
    % []Adds a label to the specified y-axis and adjusts its properties.

    %-----------------------------------------------------------------------------------------------

    plot(S.t,Tmag, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Adds a plot to the specified axes and adjusts its properties.

end