tic;clc;clear;close all;
format('Compact');
format('LongG');

currentFolder = fileparts(mfilename('fullpath'));
CodePath = fullfile(currentFolder, '..', 'SourceCode');
addpath(CodePath);

Equal = strcat(repelem('=',100));
Dash = strcat(repelem('-',100));
String = 'Preliminary Earth-Jupiter Transfer Parameters:\n';

fprintf(String);
fprintf("%s\n", Equal);

%% CONSTANTS AND PORKCHOP DATA:

C = NbpConstants;
% []Loads the Nbp constants.

load('EarthJupiterOptimalParameters.mat','Optimal');
% []Loads the data generated by the porkchop.

C.JDo = Optimal.JD;
% [solar days]Corrects the optimal departure Julian date.

%% PRELIMINARY TRAJECTORY:

to = [0, Optimal.dt];
% [s]Modeling time.

So = [Optimal.Rsatcm; Optimal.Vsatcm];
% [km,km/s]Initial satellite state WRT the CM in ECI coordinates.

Solution = ode45(@(t,S)NbpEom(t,S,C),to,So,C.IvpOptions);
% []Numerically integrates the N-Body problem.

% save('EarthJupiterPreliminaryTrajectory.mat','Solution');
% []Stores the data for the preliminary trajectory.

%% PLOT RESULTS:

R = PlotTrajectory(Solution,C,'Earth-Jupiter Transfer (Preliminary)');
% []Plots the satellite interplanetary trajectory.

PlotDepartureTrajectory(R,C,'Earth Departure');
% []Plots the satellite departure trajectory.

PlotArrivalTrajectory(R,C,'Jupiter Arrival');
% []Plots the satellite arrival trajectory.

%% PRINT RESULTS:

String = { ...
    'Departure\n%s\n'; ...
    'Departure UTC: %4.0f:%02.0f:%02.0f:%02.0f:%02.0f:%02.0f\n'; ...
    '\x0394v = %0.3f km/s\n'; ...
    '%s\n'; ...
    'Arrival\n%s\n'; ...
    'Arrival UTC: %4.0f:%02.0f:%02.0f:%02.0f:%02.0f:%02.0f\n'; ...
    '\x0394t = %0.3f days\n'; ...
    'Jupiter Distance: %0.3f JR\n'};
% []Formatted string.

UTCo = datetime(Optimal.JD,'ConvertFrom','JulianDate','Format','yyyy:MM:dd:HH:mm:ss');
% []Departure UTC as a datetime value.

UTCo = datevec(UTCo);
% [yyyy,MM,dd,HH,mm,ss]Departure UTC.

UTCf = datetime( ...
    Optimal.JD + Optimal.dt / 86400,'ConvertFrom','JulianDate','Format','yyyy:MM:dd:HH:mm:ss');
% []Arrival UTC as a datetime value.

UTCf = datevec(UTCf);
% [yyyy,MM,dd,HH,mm,ss]Arrival UTC.

dv = DepartureDeltaV(Solution,Optimal,C);
% [km/s]Departure delta-v.

R105 = (R.R10cm - R.R5cm) / C.R(5);
% [JR] Satellite position WRT Jupiter in JR

Result = {Equal; UTCo; dv; Dash; Equal; UTCf; Optimal.dt / 86400; norm(R105(:,end))};
% []Results cell.

for k = 1:length(String)

    fprintf(String{k},Result{k});
    % []Prints the formatted string on the command window.

end

%% PRINT SIMULATION TIME:

fprintf("%s\n", Equal);
%[]Prints the formatted string on the command window.

SimulationTime = toc;
%[]Stops the program timer.

SimulationTimeString = 'Simulation Time: %0.3f seconds\n';
% []Formatted string.

fprintf(SimulationTimeString,SimulationTime);
%[]Prints the simulation time on the command window.
%===================================================================================================   