function MissionSummary(S,dv,di,Dash)

    String = strcat( ...
        '(1) Launch:\n', ...
        '    UTC = %4.0f:%02.0f:%02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '    EMT = %02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '      \x03C6 = %2.0f\x00B0 %02.0f\x2032 %02.0f\x2033 N\n', ...
        '      \x03BB = %2.0f\x00B0 %02.0f\x2032 %02.0f\x2033 W\n', ...
        '     \x0394v = %0.3f km/s\n', ...
        '     \x0394i = %0.3f\x00B0\n');
    % []Formatted string.

    EMT = Sec2Dhms(S(1).t(1));
    % [days,hours,minutes,seconds]Elapsed mission time.

    Lat = degrees2dms(S(1).Lat(1));
    % [dms]Event latitude.

    Long = degrees2dms(-S(1).Long(1));
    % [dms]Event longitude.

    fprintf(String, ...
        S(1).UTC(1,:), ...
        EMT, ...
        Lat, ...
        Long, ...
        0, ...
        0);
    % []Prints the formatted string on the command window.

    fprintf(Dash);
    % []Prints the formatted string on the command window.

    %-----------------------------------------------------------------------------------------------

    String = strcat( ...
        '(2) Orbit Insertion:\n', ...
        '    UTC = %4.0f:%02.0f:%02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '    EMT = %02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '      \x03C6 = %2.0f\x00B0 %02.0f\x2032 %02.0f\x2033 N\n', ...
        '      \x03BB = %2.0f\x00B0 %02.0f\x2032 %02.0f\x2033 W\n', ...
        '     \x0394v = %0.3f km/s\n', ...
        '     \x0394i = %0.3f\x00B0\n');
    % []Formatted string.

    EMT = Sec2Dhms(S(3).t(1));
    % [days,hours,minutes,seconds]Elapsed mission time.

    Lat = degrees2dms(S(3).Lat(1));
    % [dms]Event latitude.

    Long = degrees2dms(-S(3).Long(1));
    % [dms]Event longitude.

    fprintf(String, ...
        S(3).UTC(1,:), ...
        EMT, ...
        Lat, ...
        Long, ...
        0, ...
        0);
    % []Prints the formatted string on the command window.

    fprintf(Dash);
    % []Prints the formatted string on the command window.

    %-----------------------------------------------------------------------------------------------

    String = strcat( ...
        '(3) Hohmann Transfer Departure:\n', ...
        '    UTC = %4.0f:%02.0f:%02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '    EMT = %02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '      \x03C6 = %1.0f\x00B0 %02.0f\x2032 %02.0f\x2033 S\n', ...
        '      \x03BB = %1.0f\x00B0 %02.0f\x2032 %02.0f\x2033 E\n', ...
        '     \x0394v = %0.3f km/s\n', ...
        '     \x0394i = %0.3f\x00B0\n');
    % []Formatted string.

    EMT = Sec2Dhms(S(5).t(1));
    % [days,hours,minutes,seconds]Elapsed mission time.

    Lat = degrees2dms(-S(5).Lat(1));
    % [dms]Event latitude.

    Long = degrees2dms(S(5).Long(1));
    % [dms]Event longitude.

    fprintf(String, ...
        S(5).UTC(1,:), ...
        EMT, ...
        Lat, ...
        Long, ...
        dv(1), ...
        0);
    % []Prints the formatted string on the command window.

    fprintf(Dash);
    % []Prints the formatted string on the command window.

    %-----------------------------------------------------------------------------------------------

    String = strcat( ...
        '(4) Combined Maneuver:\n', ...
        '    UTC = %4.0f:%02.0f:%02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '    EMT = %02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '      \x03C6 = %3.0f\x00B0 %02.0f\x2032 %02.0f\x2033 N\n', ...
        '      \x03BB = %3.0f\x00B0 %02.0f\x2032 %02.0f\x2033 E\n', ...
        '     \x0394v = %0.3f km/s\n', ...
        '     \x0394i = %0.3f\x00B0\n');
    % []Formatted string.

    EMT = Sec2Dhms(S(7).t(1));
    % [days,hours,minutes,seconds]Elapsed mission time.

    Lat = degrees2dms(S(7).Lat(1));
    % [dms]Event latitude.

    Long = degrees2dms(S(7).Long(1));
    % [dms]Event longitude.

    fprintf(String, ...
        S(7).UTC(1,:), ...
        EMT, ...
        Lat, ...
        Long, ...
        dv(2), ...
        di);
    % []Prints the formatted string on the command window.

    fprintf(Dash);
    % []Prints the formatted string on the command window.

    %-----------------------------------------------------------------------------------------------

    String = strcat( ...
        '(5) Correction Maneuver:\n', ...
        '    UTC = %4.0f:%02.0f:%02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '    EMT = %02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '      \x03C6 = %3.0f\x00B0 %02.0f\x2032 %02.0f\x2033 N\n', ...
        '      \x03BB = %3.0f\x00B0 %02.0f\x2032 %02.0f\x2033 W\n', ...
        '     \x0394v = %0.3f km/s\n', ...
        '     \x0394i = %0.3f\x00B0\n');
    % []Formatted string.

    EMT = Sec2Dhms(S(9).t(1));
    % [days,hours,minutes,seconds]Elapsed mission time.

    Lat = degrees2dms(S(9).Lat(1));
    % [dms]Event latitude.

    Long = -1 * degrees2dms(S(9).Long(1));
    % [dms]Event longitude.

    fprintf(String, ...
        S(5).UTC(end,:), ...
        EMT, ...
        Lat, ...
        Long, ...
        dv(3), ...
        0);
    % []Prints the formatted string on the command window.

        %-----------------------------------------------------------------------------------------------

    String = strcat( ...
        '(6) Mission Conclusion:\n', ...
        '    UTC = %4.0f:%02.0f:%02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '    EMT = %02.0f:%02.0f:%02.0f:%02.0f\n', ...
        '      \x03C6 = %3.0f\x00B0 %02.0f\x2032 %02.0f\x2033 N\n', ...
        '      \x03BB = %3.0f\x00B0 %02.0f\x2032 %02.0f\x2033 W\n', ...
        '     \x0394v = %0.3f km/s\n', ...
        '     \x0394i = %0.3f\x00B0\n');
    % []Formatted string.

    EMT = Sec2Dhms(S(9).t(end));
    % [days,hours,minutes,seconds]Elapsed mission time.

    Lat = degrees2dms(S(9).Lat(end));
    % [dms]Event latitude.

    Long = -1 * degrees2dms(S(9).Long(end));
    % [dms]Event longitude.

    fprintf(String, ...
        S(9).UTC(end,:), ...
        EMT, ...
        Lat, ...
        Long, ...
        0, ...
        0);
    % []Prints the formatted string on the command window.

end
%===================================================================================================